/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class Trabajo extends javax.swing.JFrame {

    /**
     * Creates new form Trabajo
     */
    public Trabajo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label_fechaCorte = new javax.swing.JLabel();
        label_fechaFacturacion = new javax.swing.JLabel();
        txt_day = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        cbo_mon = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dia de desembolso:");

        label_fechaCorte.setText("fecha de corte");

        label_fechaFacturacion.setText("fecha de facturacion");

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        cbo_mon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbo_mon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_monItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_fechaCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_fechaFacturacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbo_mon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_day, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btn_calcular)
                        .addGap(39, 39, 39)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(cbo_mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_fechaCorte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_fechaFacturacion)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // TODO add your handling code here:
        
       
        //declaracion de dias de facturacion
        int diasFacturacion[]=new int[4];
        diasFacturacion[0]=2;
        diasFacturacion[1]=10;
        diasFacturacion[2]=15;
        diasFacturacion[3]=25;
        //declaracion de fechas maximas de cada mes
         int maxMeses[]= new int[12];
        maxMeses[0] = 31;
        maxMeses[1] = 28;
        maxMeses[2] = 31;
        maxMeses[3] = 30;
        maxMeses[4] = 31;
        maxMeses[5] = 30;
        maxMeses[6] = 31;
        maxMeses[7] = 31;
        maxMeses[8] = 30;
        maxMeses[9] = 31;
        maxMeses[10] = 30;
        maxMeses[11] = 31;
        try {
             //recuperacion de datos del formulario
            int date = Integer.parseInt(txt_day.getText());
            int valor_mes_formulario = cbo_mon.getSelectedIndex();
            //validacion de mensaje
             message(valor_mes_formulario, maxMeses, date);
            //para hallar la fecha de corte
            int valor_mes_fecha_corte=0;
            int fecha_de_corte = 0;
            for (int i = 0; i < diasFacturacion.length; i++) {
                if(diasFacturacion[i]>date){

                    fecha_de_corte = diasFacturacion[i];
                    valor_mes_fecha_corte=valor_mes_formulario;
                    label_fechaCorte.setText("La fecha de corte seria: " + fecha_de_corte + " de " + cbo_mon.getItemAt(valor_mes_fecha_corte));
                    break;
                }
                else if(date > diasFacturacion[i] && date > diasFacturacion[diasFacturacion.length-1]){
                    fecha_de_corte = diasFacturacion[0];
                    valor_mes_fecha_corte=valor_mes_formulario+1;
                    if(valor_mes_formulario==12){
                        valor_mes_fecha_corte=1;
                    }
                    label_fechaCorte.setText("La fecha de corte seria: " + fecha_de_corte + " de " + cbo_mon.getItemAt(valor_mes_fecha_corte));
                    break;
                }            
            }
            //hallar la fecha provicional
            int valor_mes_fecha_facturacion=0;
            int fecha_provicional = 0;
            int residuo_mes=0;
            if(fecha_de_corte < 12){
                fecha_provicional = fecha_de_corte + 15;
                valor_mes_fecha_facturacion=valor_mes_fecha_corte;
            }
            else{
               fecha_provicional = fecha_de_corte + 15;
               if(fecha_provicional > maxMeses[valor_mes_fecha_corte-1]){
                   residuo_mes=fecha_provicional-maxMeses[valor_mes_fecha_corte-1];
                   fecha_provicional = residuo_mes;
                   valor_mes_fecha_facturacion = valor_mes_fecha_corte+1;
                   if(valor_mes_fecha_facturacion==13){
                       valor_mes_fecha_facturacion=1;
                   }
               }
               else{
                    valor_mes_fecha_facturacion = valor_mes_fecha_corte+1; 
               }
            }
            //calculo de la aproximacion del dia de facturacion
            int fecha_facturacion=0;
            int residuoIzquierda=0;
            int residuoDerecha=0;
            for (int i = 0; i < diasFacturacion.length; i++) {
                if(diasFacturacion[i] < fecha_provicional && diasFacturacion[i+1]> fecha_provicional){
                    residuoIzquierda = fecha_provicional-diasFacturacion[i];
                    residuoDerecha = diasFacturacion[i+1]-fecha_provicional;
                    if(residuoIzquierda < residuoDerecha){
                        fecha_facturacion= diasFacturacion[i];
                    }
                    else{
                        fecha_facturacion= diasFacturacion[i+1];
                    }
                }
                else if(fecha_provicional > diasFacturacion[diasFacturacion.length-1]){
                    fecha_facturacion= diasFacturacion[0];
                    break;
                }
                else if(fecha_provicional==diasFacturacion[i]){
                    fecha_facturacion= diasFacturacion[i];
                    break;
                }
            }
            label_fechaFacturacion.setText("La fecha de facturacion seria: " + fecha_provicional +" - "+fecha_facturacion+ " de " + cbo_mon.getItemAt(valor_mes_fecha_facturacion));
        
        } catch (Exception e) {
            int valor_mes_formulario = cbo_mon.getSelectedIndex();
            if(valor_mes_formulario==0){
                JOptionPane.showMessageDialog(this, "Debe seleccionar un mes");
            }
            else{
                JOptionPane.showMessageDialog(this, "Debe ingresar un dia de desembolso");
            }
        }
        
       
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void cbo_monItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_monItemStateChanged
        // TODO add your handling code here:
        int pos=cbo_mon.getSelectedIndex();
        if(pos!=0){
            status(1);
        }
        else{
            status(0);
        }
    }//GEN-LAST:event_cbo_monItemStateChanged

     public void message(int valor_mes_formulario,int maxMeses[],int day){
        String mes = cbo_mon.getItemAt(valor_mes_formulario);
        String message="El mes de "+ mes+" no tiene "+day+" dias.";
        for (int i = 0; i < maxMeses.length; i++) {
            if(i==valor_mes_formulario-1 && maxMeses[i]<day){
                JOptionPane.showMessageDialog(this, message);
                txt_day.setText("");
                break;
            }
        }
    }
     public void fechaCorte(int diasFacturacion[],int date,int valor_mes_formulario){
         int fecha_de_corte = 0;
         int valor_mes_fecha_corte=0;
        for (int i = 0; i < diasFacturacion.length; i++) {
            if(diasFacturacion[i]>date){
                
                fecha_de_corte = diasFacturacion[i];
                valor_mes_fecha_corte=valor_mes_formulario;
                 label_fechaCorte.setText("La fecha de corte seria: " + fecha_de_corte + " de " + cbo_mon.getItemAt(valor_mes_fecha_corte));
                break;
            }
            else if(date > diasFacturacion[i] && date > diasFacturacion[diasFacturacion.length-1]){
                fecha_de_corte = diasFacturacion[0];
                valor_mes_fecha_corte=valor_mes_formulario+1;
                if(valor_mes_formulario==12){
                    valor_mes_fecha_corte=1;
                }
                label_fechaCorte.setText("La fecha de corte seria: " + fecha_de_corte + " de " + cbo_mon.getItemAt(valor_mes_fecha_corte));
                break;
            }            
        }
     }
     public void status(int status){
        if(status==0){
            btn_calcular.setEnabled(false);
            txt_day.setEnabled(false);
        }
        else{
             btn_calcular.setEnabled(true);
             txt_day.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JComboBox<String> cbo_mon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_fechaCorte;
    private javax.swing.JLabel label_fechaFacturacion;
    private javax.swing.JTextField txt_day;
    // End of variables declaration//GEN-END:variables
}
