/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Luis
 */
public class View_Day extends javax.swing.JFrame {

    /**
     * Creates new form View_Day
     */
    public View_Day() {
        initComponents();
         setLocationRelativeTo(null);
         setResizable(false);
         status(1);
//         SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MagmaSkin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_day = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        label_fechaCorte = new javax.swing.JLabel();
        cbo_mon = new javax.swing.JComboBox<>();
        label_fechaFacturacion = new javax.swing.JLabel();
        cbo_pos1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("Dia de desembolso:");

        txt_day.setEnabled(false);

        btn_calcular.setText("Calcular");
        btn_calcular.setEnabled(false);
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        label_fechaCorte.setText("fecha de corte");

        cbo_mon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbo_mon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_monItemStateChanged(evt);
            }
        });

        label_fechaFacturacion.setText("fecha de facturacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbo_mon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_day, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btn_calcular)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_fechaCorte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_fechaFacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_calcular)
                    .addComponent(cbo_mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_fechaCorte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_fechaFacturacion)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        cbo_pos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RavenGraphite", "AutumnSkin", "Business", "Creme", "EmeraldDusk", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10", "Item 11", "Item 12", "Item 13", "Item 14", "Item 15", "Item 16", "Item 17", "Item 18", "Item 19" }));
        cbo_pos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_pos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbo_pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(cbo_pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void status(int status){
        if(status==0){
            btn_calcular.setEnabled(false);
            txt_day.setEnabled(false);
        }
        else{
             btn_calcular.setEnabled(true);
            txt_day.setEnabled(true);
        }
    }
    public void message(int pos,int day){
        String message="El dia no esta en el rango del mes";
        if(pos==1){
            if(day > 31)
                JOptionPane.showMessageDialog(this, message);
        }
        else if(pos==2){
            if(day > 28)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==3){
            if(day > 31)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==4){
            if(day > 30)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==5){
            if(day > 31)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==6){
            if(day > 30)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==7){
            if(day > 31)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==8){
            if(day > 31)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==9){
            if(day > 30)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==10){
            if(day > 31)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==11){
            if(day > 30)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(pos==12){
            if(day > 31)
                JOptionPane.showMessageDialog(this, message);
        }
         else if(day < 1){
             JOptionPane.showMessageDialog(this, message);
         }
         else{
             JOptionPane.showMessageDialog(this, "Ponga una fecha");
         }
      
    }
    public void message2(int pos,int maxMeses[],int day){
        String message="El dia no esta en el rango del mes";
        for (int i = 0; i < maxMeses.length; i++) {
            if(i==pos-1 && maxMeses[i]<day){
                JOptionPane.showMessageDialog(this, message);
                break;
            }
        }
      
    }
    public int fechaFacturacion(int day, int maxMeses[],int diasFacturacion[],int mes){
        int diaNew=22;
        int mesNew=4;
        int FechaFacturacion=0;
        return mesNew;
    }
    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // TODO add your handling code here:
        try {
            int day = Integer.parseInt(txt_day.getText());
            int posMesInicial=cbo_mon.getSelectedIndex();
            String nombreMes= cbo_mon.getItemAt(posMesInicial);
            int diasFacturacion[]=new int[4];
            diasFacturacion[0]=2;
            diasFacturacion[1]=10;
            diasFacturacion[2]=15;
            diasFacturacion[3]=25;
            
            int maxMeses[]= new int[12];
            maxMeses[0] = 31;
            maxMeses[1] = 28;
            maxMeses[2] = 31;
            maxMeses[3] = 30;
            maxMeses[4] = 31;
            maxMeses[5] = 30;
            maxMeses[6] = 31;
            maxMeses[7] = 31;
            maxMeses[8] = 30;
            maxMeses[9] = 31;
            maxMeses[10] = 30;
            maxMeses[11] = 31;
   
            int fechaCorte = 0;
            if(day<2){
                fechaCorte=2;
            }
            else if(day>=2 && day<10){
                fechaCorte=10;
            }
            else if(day>=10 && day<15){
                fechaCorte=15;
            }
            else if(day>=15 && day<25){
                fechaCorte=25;
            }
            else if(day>=25){
                fechaCorte=2;
                nombreMes=cbo_mon.getItemAt(posMesInicial+1);
                if(posMesInicial==12){
                    nombreMes=cbo_mon.getItemAt(1);
                }
            }
            
            int fechaFacturacion=0;
            String nombreMesFacturacion=cbo_mon.getItemAt(posMesInicial);
            if(fechaCorte == 2 ){
                fechaFacturacion = 15;
                if(posMesInicial==12){
                    nombreMesFacturacion=cbo_mon.getItemAt(1);
                }
                else
                {
                    nombreMesFacturacion=cbo_mon.getItemAt(posMesInicial+1);
                }
            }
            else if(fechaCorte == 10){
                fechaFacturacion= 25;
                if(posMesInicial==12){
                    nombreMesFacturacion=cbo_mon.getItemAt(1);
                }
                else
                {
                    nombreMesFacturacion=cbo_mon.getItemAt(posMesInicial+1);
                }
            }
            else if(fechaCorte == 15){
                fechaFacturacion = 2;
                nombreMesFacturacion=cbo_mon.getItemAt(posMesInicial+1);
                if(posMesInicial==12){
                    nombreMesFacturacion=cbo_mon.getItemAt(1);
                }
                else
                {
                    nombreMesFacturacion=cbo_mon.getItemAt(posMesInicial+1);
                }
            }
            else if(fechaCorte == 25){
                fechaFacturacion= 10;
                if(posMesInicial==12){
                    nombreMesFacturacion=cbo_mon.getItemAt(1);
                }
                else
                {
                    nombreMesFacturacion=cbo_mon.getItemAt(posMesInicial+1);
                }
            }
            label_fechaFacturacion.setText("La fecha de facturacion seria "+fechaFacturacion+" de "+nombreMesFacturacion);
            label_fechaCorte.setText("La fecha de Corte seria "+fechaCorte+ " de "+ nombreMes);
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Solo se permiten valores enteros");
            txt_day.setText("");
        }         
         int mesNew=4;
//            int reciduo= 0;
//            int diferencia[]= new int[4];
//            int MaxDiferencia=0;
//            String diferenciass="";
//            for (int i = 0; i < diasFacturacion.length; i++) {
//              
//               reciduo=diasFacturacion[i]- diaNew;
//               diferencia[i]=reciduo;
//               diferenciass= diferenciass+" "+diferencia[i];
//            }
//            
//            for (int i = 0; i < diferencia.length; i++) {
//                if(diferencia[i]>MaxDiferencia){
//                    MaxDiferencia = diferencia[i];
//                    break;
//                }
//            }
//            String nameMeses[]= new String[12];
//            nameMeses[0]="Enero";
//            nameMeses[1]="Febrero";
//            nameMeses[2]="Marzo";
//            nameMeses[3]="Abril";
//            nameMeses[4]="Mayo";
//            nameMeses[5]="Junio";
//            nameMeses[6]="Julio";
//            nameMeses[7]="Agosto";
//            nameMeses[8]="Septiembre";
//            nameMeses[9]="Octubre";
//            nameMeses[10]="Nombriembre";
//            nameMeses[11]="Diciembre";
//            message(pos, day);
//            message(pos, day);
        
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void cbo_monItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_monItemStateChanged
        // TODO add your handling code here:
        int pos=cbo_mon.getSelectedIndex();
        if(pos!=0){
            status(1);
        }
        else{
            status(0);
        }
    }//GEN-LAST:event_cbo_monItemStateChanged

    private void cbo_pos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_pos1ActionPerformed
        // TODO add your handling code here:
        int pos=cbo_pos1.getSelectedIndex();
        switch(pos)
        {
            case 0:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenGraphiteSkin");break;
            case 1:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.AutumnSkin");break;
            case 2:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessSkin");break;
            case 3:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.CremeSkin");break;
            case 4:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.EmeraldDuskSkin");break;
            case 5:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.GreenMagicSkin");break;
            case 6:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MagmaSkin");break;
            case 7:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MangoSkin");break;
            case 8:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MistAquaSkin");break;
            case 9:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MistSilverSkin");break;
            case 10:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.ModerateSkin");break;
            case 11:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.NebulaBrickWallSkin");break;
            case 12:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.NebulaSkin");break;
            case 13:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.OfficeBlue2007Skin");break;
            case 14:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.OfficeSilver2007Skin");break;
            case 15:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenGraphiteGlassSkin");break;
            case 16:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenGraphiteSkin");break;
            case 17:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenSkin");break;
            case 18:
            SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.SaharaSkin");break;

        }
    }//GEN-LAST:event_cbo_pos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Day.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Day.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Day.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Day.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Day().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JComboBox<String> cbo_mon;
    private javax.swing.JComboBox<String> cbo_pos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_fechaCorte;
    private javax.swing.JLabel label_fechaFacturacion;
    private javax.swing.JTextField txt_day;
    // End of variables declaration//GEN-END:variables

    private void swtich() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
